spring.application.name=InterviewTracker

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/interview_tracker
spring.datasource.username=root
spring.datasource.password=beach

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Server
server.port=8081